name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      CDK_DEFAULT_ACCOUNT: ${{secrets.AWS_ACCOUNT_ID}}
      CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      DB_NAME: ${{secrets.DB_NAME}}    
      DB_HOST: ${{secrets.DB_HOST}}    
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_PORT: ${{secrets.DB_PORT}}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      RESET_PASSWORD: ${{ secrets.RESET_PASSWORD }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }} 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
      
      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      
      - name: Install dependencies
        run: npm ci

      - name: Compile CDK (TypeScript)
        run: npm run compile:cdk
      
      - name: CDK Synth
        run: npx cdk synth
        
      - name: Deploy with CDK
        run: npx cdk deploy --require-approval never --ci --outputs-file cdk-outputs.json

      - name: Show API URL
        id: show-api
        run: |
          API_URL=$(jq -r '.BackendStack | to_entries[] | select(.key | contains("ParkingAPIEndpointV2")) | .value' cdk-outputs.json | head -n 1)
          echo "Parking API Endpoint: $API_URL"
          echo "API_URL=$API_URL" >> $GITHUB_ENV

      - name: Test API URL
        run: |
          echo "Using Parking API URL: $API_URL"
          curl -s "$API_URL/auth/users"
            